// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reservation.proto

package reservations

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reservation struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Venue                string    `protobuf:"bytes,3,opt,name=venue,proto3" json:"venue,omitempty"`
	Room                 string    `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	Timestamp            string    `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attendees            []*Person `protobuf:"bytes,6,rep,name=attendees,proto3" json:"attendees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{0}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reservation) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Reservation) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Reservation) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *Reservation) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Reservation) GetAttendees() []*Person {
	if m != nil {
		return m.Attendees
	}
	return nil
}

type Person struct {
	Ssn                  string   `protobuf:"bytes,1,opt,name=ssn,proto3" json:"ssn,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetSsn() string {
	if m != nil {
		return m.Ssn
	}
	return ""
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateReservationRequest struct {
	Reservation          *Reservation `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateReservationRequest) Reset()         { *m = CreateReservationRequest{} }
func (m *CreateReservationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReservationRequest) ProtoMessage()    {}
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{2}
}

func (m *CreateReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReservationRequest.Unmarshal(m, b)
}
func (m *CreateReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReservationRequest.Marshal(b, m, deterministic)
}
func (m *CreateReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReservationRequest.Merge(m, src)
}
func (m *CreateReservationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReservationRequest.Size(m)
}
func (m *CreateReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReservationRequest proto.InternalMessageInfo

func (m *CreateReservationRequest) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type DeleteReservationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationRequest) Reset()         { *m = DeleteReservationRequest{} }
func (m *DeleteReservationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationRequest) ProtoMessage()    {}
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{3}
}

func (m *DeleteReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationRequest.Unmarshal(m, b)
}
func (m *DeleteReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationRequest.Merge(m, src)
}
func (m *DeleteReservationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationRequest.Size(m)
}
func (m *DeleteReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationRequest proto.InternalMessageInfo

func (m *DeleteReservationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetReservationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationRequest) Reset()         { *m = GetReservationRequest{} }
func (m *GetReservationRequest) String() string { return proto.CompactTextString(m) }
func (*GetReservationRequest) ProtoMessage()    {}
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{4}
}

func (m *GetReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationRequest.Unmarshal(m, b)
}
func (m *GetReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationRequest.Marshal(b, m, deterministic)
}
func (m *GetReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationRequest.Merge(m, src)
}
func (m *GetReservationRequest) XXX_Size() int {
	return xxx_messageInfo_GetReservationRequest.Size(m)
}
func (m *GetReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationRequest proto.InternalMessageInfo

func (m *GetReservationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListReservationRequest struct {
	Venue                string                           `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	Title                string                           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Room                 string                           `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Attendes             *ListReservationRequest_Attendes `protobuf:"bytes,4,opt,name=attendes,proto3" json:"attendes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListReservationRequest) Reset()         { *m = ListReservationRequest{} }
func (m *ListReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ListReservationRequest) ProtoMessage()    {}
func (*ListReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{5}
}

func (m *ListReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReservationRequest.Unmarshal(m, b)
}
func (m *ListReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReservationRequest.Marshal(b, m, deterministic)
}
func (m *ListReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReservationRequest.Merge(m, src)
}
func (m *ListReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ListReservationRequest.Size(m)
}
func (m *ListReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReservationRequest proto.InternalMessageInfo

func (m *ListReservationRequest) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *ListReservationRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListReservationRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *ListReservationRequest) GetAttendes() *ListReservationRequest_Attendes {
	if m != nil {
		return m.Attendes
	}
	return nil
}

type ListReservationRequest_Attendes struct {
	Lastname             []string `protobuf:"bytes,1,rep,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReservationRequest_Attendes) Reset()         { *m = ListReservationRequest_Attendes{} }
func (m *ListReservationRequest_Attendes) String() string { return proto.CompactTextString(m) }
func (*ListReservationRequest_Attendes) ProtoMessage()    {}
func (*ListReservationRequest_Attendes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{5, 0}
}

func (m *ListReservationRequest_Attendes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReservationRequest_Attendes.Unmarshal(m, b)
}
func (m *ListReservationRequest_Attendes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReservationRequest_Attendes.Marshal(b, m, deterministic)
}
func (m *ListReservationRequest_Attendes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReservationRequest_Attendes.Merge(m, src)
}
func (m *ListReservationRequest_Attendes) XXX_Size() int {
	return xxx_messageInfo_ListReservationRequest_Attendes.Size(m)
}
func (m *ListReservationRequest_Attendes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReservationRequest_Attendes.DiscardUnknown(m)
}

var xxx_messageInfo_ListReservationRequest_Attendes proto.InternalMessageInfo

func (m *ListReservationRequest_Attendes) GetLastname() []string {
	if m != nil {
		return m.Lastname
	}
	return nil
}

func init() {
	proto.RegisterType((*Reservation)(nil), "reservations.Reservation")
	proto.RegisterType((*Person)(nil), "reservations.Person")
	proto.RegisterType((*CreateReservationRequest)(nil), "reservations.CreateReservationRequest")
	proto.RegisterType((*DeleteReservationRequest)(nil), "reservations.DeleteReservationRequest")
	proto.RegisterType((*GetReservationRequest)(nil), "reservations.GetReservationRequest")
	proto.RegisterType((*ListReservationRequest)(nil), "reservations.ListReservationRequest")
	proto.RegisterType((*ListReservationRequest_Attendes)(nil), "reservations.ListReservationRequest.Attendes")
}

func init() { proto.RegisterFile("reservation.proto", fileDescriptor_c1b272c5347b2042) }

var fileDescriptor_c1b272c5347b2042 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0xb8, 0x8d, 0x92, 0x31, 0x94, 0x66, 0x94, 0x56, 0xc6, 0xe4, 0x10, 0x2d, 0xa8,
	0x54, 0x95, 0xb0, 0x91, 0xb9, 0xc1, 0x09, 0x01, 0x42, 0x48, 0x08, 0x21, 0x83, 0xc4, 0xd9, 0x25,
	0xd3, 0x6a, 0x25, 0xdb, 0x1b, 0xbc, 0x9b, 0x48, 0x80, 0xb8, 0xf0, 0x0a, 0x3c, 0x08, 0x0f, 0xc2,
	0x91, 0x33, 0x37, 0x1e, 0xa4, 0xf2, 0xae, 0x9d, 0xac, 0x53, 0xa7, 0xca, 0xcd, 0xfb, 0xcf, 0xec,
	0xfe, 0xb3, 0xff, 0xe7, 0x85, 0x51, 0x49, 0x92, 0xca, 0x65, 0xaa, 0xb8, 0x28, 0xc2, 0x79, 0x29,
	0x94, 0xc0, 0x5b, 0x96, 0x24, 0x83, 0x7b, 0x97, 0x42, 0x5c, 0x66, 0x14, 0xe9, 0xda, 0xf9, 0xe2,
	0x22, 0xa2, 0x7c, 0xae, 0xbe, 0x9a, 0xd6, 0x60, 0x52, 0x17, 0xd3, 0x39, 0x8f, 0xd2, 0xa2, 0x10,
	0xca, 0x6c, 0x32, 0x55, 0xf6, 0xdb, 0x01, 0x2f, 0x59, 0x9f, 0x85, 0x07, 0xd0, 0xe3, 0x33, 0xdf,
	0x99, 0x3a, 0xa7, 0xc3, 0xa4, 0xc7, 0x67, 0x38, 0x86, 0x7d, 0xc5, 0x55, 0x46, 0x7e, 0x4f, 0x4b,
	0x66, 0x51, 0xa9, 0x4b, 0x2a, 0x16, 0xe4, 0xbb, 0x46, 0xd5, 0x0b, 0x44, 0xd8, 0x2b, 0x85, 0xc8,
	0xfd, 0x3d, 0x2d, 0xea, 0x6f, 0x9c, 0xc0, 0x50, 0xf1, 0x9c, 0xa4, 0x4a, 0xf3, 0xb9, 0xbf, 0xaf,
	0x0b, 0x6b, 0x01, 0x63, 0x18, 0xa6, 0x4a, 0x51, 0x31, 0x23, 0x92, 0x7e, 0x7f, 0xea, 0x9e, 0x7a,
	0xf1, 0x38, 0xb4, 0xaf, 0x16, 0xbe, 0xa7, 0x52, 0x8a, 0x22, 0x59, 0xb7, 0xb1, 0x8f, 0xd0, 0x37,
	0x22, 0x1e, 0x82, 0x2b, 0x65, 0x51, 0x0f, 0x5b, 0x7d, 0x56, 0x6e, 0x17, 0xbc, 0x94, 0xea, 0x5d,
	0x9a, 0x37, 0x13, 0xaf, 0x05, 0x0c, 0x60, 0x90, 0xa5, 0x75, 0xd1, 0x0c, 0xbe, 0x5a, 0xb3, 0x4f,
	0xe0, 0xbf, 0x28, 0x29, 0x55, 0x64, 0x85, 0x91, 0xd0, 0x97, 0x05, 0x49, 0x85, 0xcf, 0xc0, 0xb3,
	0x66, 0xd2, 0xe7, 0x7a, 0xf1, 0xdd, 0xf6, 0x9c, 0xf6, 0x36, 0xbb, 0x9b, 0x9d, 0x81, 0xff, 0x92,
	0x32, 0xea, 0x3c, 0x78, 0x23, 0x6c, 0xf6, 0x10, 0x8e, 0x5e, 0x93, 0xda, 0xa1, 0xf1, 0x8f, 0x03,
	0xc7, 0x6f, 0xb9, 0xec, 0x6a, 0x5d, 0xa1, 0x71, 0x6c, 0x34, 0xdd, 0x18, 0x1b, 0x60, 0xae, 0x05,
	0xec, 0x0d, 0x0c, 0xea, 0xac, 0xa5, 0x06, 0xe9, 0xc5, 0x8f, 0xda, 0x37, 0xed, 0xf6, 0x0d, 0x9f,
	0xd7, 0x9b, 0x92, 0xd5, 0xf6, 0xe0, 0x04, 0x06, 0x8d, 0xda, 0x64, 0x5f, 0x54, 0xd9, 0x3b, 0x53,
	0xb7, 0xc9, 0xbe, 0x5a, 0xc7, 0xff, 0x5c, 0x40, 0xeb, 0xc4, 0x0f, 0x54, 0x2e, 0xf9, 0x67, 0xc2,
	0x6f, 0x30, 0xba, 0x86, 0x04, 0x4f, 0xda, 0xc3, 0x6c, 0x63, 0x16, 0x6c, 0xc7, 0xc3, 0xd8, 0xcf,
	0xbf, 0xff, 0x7f, 0xf5, 0x26, 0xec, 0x76, 0x64, 0xb7, 0x3c, 0xb5, 0xa9, 0xa1, 0x80, 0xd1, 0x35,
	0x6a, 0x9b, 0xde, 0xdb, 0xb0, 0x06, 0xc7, 0xa1, 0x79, 0x72, 0x61, 0xf3, 0x1e, 0xc3, 0x57, 0xd5,
	0x7b, 0x64, 0x81, 0x36, 0x1e, 0x9f, 0x61, 0xcb, 0x38, 0xfa, 0xce, 0x67, 0x3f, 0x30, 0x83, 0x83,
	0x36, 0x7a, 0xbc, 0xdf, 0x76, 0xeb, 0xfc, 0x31, 0x6e, 0xba, 0x66, 0xed, 0x86, 0xdd, 0x6e, 0x87,
	0x1b, 0x18, 0x25, 0x3e, 0xd8, 0x05, 0xf3, 0x4d, 0x86, 0x47, 0xda, 0xf0, 0x0e, 0xb6, 0x73, 0x7d,
	0xec, 0x9c, 0xf7, 0x75, 0x0e, 0x4f, 0xae, 0x02, 0x00, 0x00, 0xff, 0xff, 0x43, 0x98, 0x6d, 0x8a,
	0xc8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReservationServiceClient is the client API for ReservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReservationServiceClient interface {
	CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*Reservation, error)
	DeleteReservation(ctx context.Context, in *DeleteReservationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*Reservation, error)
	ListReservations(ctx context.Context, in *ListReservationRequest, opts ...grpc.CallOption) (ReservationService_ListReservationsClient, error)
}

type reservationServiceClient struct {
	cc *grpc.ClientConn
}

func NewReservationServiceClient(cc *grpc.ClientConn) ReservationServiceClient {
	return &reservationServiceClient{cc}
}

func (c *reservationServiceClient) CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*Reservation, error) {
	out := new(Reservation)
	err := c.cc.Invoke(ctx, "/reservations.ReservationService/CreateReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) DeleteReservation(ctx context.Context, in *DeleteReservationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/reservations.ReservationService/DeleteReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*Reservation, error) {
	out := new(Reservation)
	err := c.cc.Invoke(ctx, "/reservations.ReservationService/GetReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationServiceClient) ListReservations(ctx context.Context, in *ListReservationRequest, opts ...grpc.CallOption) (ReservationService_ListReservationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReservationService_serviceDesc.Streams[0], "/reservations.ReservationService/ListReservations", opts...)
	if err != nil {
		return nil, err
	}
	x := &reservationServiceListReservationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReservationService_ListReservationsClient interface {
	Recv() (*Reservation, error)
	grpc.ClientStream
}

type reservationServiceListReservationsClient struct {
	grpc.ClientStream
}

func (x *reservationServiceListReservationsClient) Recv() (*Reservation, error) {
	m := new(Reservation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReservationServiceServer is the server API for ReservationService service.
type ReservationServiceServer interface {
	CreateReservation(context.Context, *CreateReservationRequest) (*Reservation, error)
	DeleteReservation(context.Context, *DeleteReservationRequest) (*empty.Empty, error)
	GetReservation(context.Context, *GetReservationRequest) (*Reservation, error)
	ListReservations(*ListReservationRequest, ReservationService_ListReservationsServer) error
}

// UnimplementedReservationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReservationServiceServer struct {
}

func (*UnimplementedReservationServiceServer) CreateReservation(ctx context.Context, req *CreateReservationRequest) (*Reservation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReservation not implemented")
}
func (*UnimplementedReservationServiceServer) DeleteReservation(ctx context.Context, req *DeleteReservationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReservation not implemented")
}
func (*UnimplementedReservationServiceServer) GetReservation(ctx context.Context, req *GetReservationRequest) (*Reservation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReservation not implemented")
}
func (*UnimplementedReservationServiceServer) ListReservations(req *ListReservationRequest, srv ReservationService_ListReservationsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListReservations not implemented")
}

func RegisterReservationServiceServer(s *grpc.Server, srv ReservationServiceServer) {
	s.RegisterService(&_ReservationService_serviceDesc, srv)
}

func _ReservationService_CreateReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).CreateReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.ReservationService/CreateReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).CreateReservation(ctx, req.(*CreateReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_DeleteReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).DeleteReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.ReservationService/DeleteReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).DeleteReservation(ctx, req.(*DeleteReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_GetReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServiceServer).GetReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.ReservationService/GetReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServiceServer).GetReservation(ctx, req.(*GetReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReservationService_ListReservations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListReservationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReservationServiceServer).ListReservations(m, &reservationServiceListReservationsServer{stream})
}

type ReservationService_ListReservationsServer interface {
	Send(*Reservation) error
	grpc.ServerStream
}

type reservationServiceListReservationsServer struct {
	grpc.ServerStream
}

func (x *reservationServiceListReservationsServer) Send(m *Reservation) error {
	return x.ServerStream.SendMsg(m)
}

var _ReservationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reservations.ReservationService",
	HandlerType: (*ReservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReservation",
			Handler:    _ReservationService_CreateReservation_Handler,
		},
		{
			MethodName: "DeleteReservation",
			Handler:    _ReservationService_DeleteReservation_Handler,
		},
		{
			MethodName: "GetReservation",
			Handler:    _ReservationService_GetReservation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListReservations",
			Handler:       _ReservationService_ListReservations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reservation.proto",
}
